# Generated by Django 2.1.4 on 2018-12-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='wind_direction',
            field=models.CharField(max_length=2),
        ),
    ]
