# Generated by Django 2.1.3 on 2018-11-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='room',
            field=models.CharField(choices=[('0', 'Ground Floor'), (' 1', '1st Floor'), (' 2', '2nd Floor'), ('2-PC', 'Computer Room'), ('3', 'Library')], default='0', max_length=4),
        ),
    ]
